<html>
<body>
    <table celpadding="0" cellspacing="0" align="center" bgcolor="#ffffff" style="max-width:640px;min-width:320px">
        <tbody>
            <tr>
                <td align="center" height="60" bgcolor="#ffffff" style="border-top:4px solid #00b386;line-height:0px;font-size: 17px">Mission Enviro</td>
            </tr>

            <tr>
                <td height="20" style="line-height:0px;border-top:1px solid #d9d9d9"></td>
            </tr>

            <tr>
                <td align="left" style="font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:bold;color:#52555a;padding-left:10px;padding-right:10px">{!! $msg !!}</td>
            </tr>

            <tr>
                <td height="25" style="line-height:0px"></td>
            </tr>

            <tr>
                <td align="center">
                    <table width="500" border="0" cellspacing="0" cellpadding="0" align="center" bgcolor="#f7f7f7" style="border-radius:8px;border:0px solid #bcbcbc">
                        <tbody>
                            <tr>
                                <td height="30"></td>
                            </tr>
                            <tr>
                                <td style="font-family:Arial,Helvetica,sans-serif;font-size:25px; font-weight:bold;text-align:center;color:#52555a;padding-left:30px;padding-right:30px">{{ $otp }}</td>
                            </tr>
                            <tr>
                                <td height="30"></td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>

            <tr>
                <td height="25" style="line-height:0px"></td>
            </tr>

            <tr>
                <td align="left" style="font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:bold;color:#52555a;padding-left:10px;padding-right:10px">This email is automatically generated by the system. Please do not reply to this email.</td>
            </tr>

            <tr>
                <td height="25" style="line-height:0px"></td>
            </tr>

            <tr>
                <td align="left" style="font-family:Arial,Helvetica,sans-serif;font-size:15px;font-weight:bold;color:#52555a;padding-left:10px;padding-right:10px">Thank you.</td>
            </tr>

            <tr>
                <td height="30" style="line-height:0px"></td>
            </tr>
        </tbody>
    </table>
</body>
</html>